### ISSUE TITLE
Pull Rerquest

### ISSUE THREAD

**Issue by Luis-Rodes** [Luis-Rodes/practica_dwec_gestor_presupuesto#1]
Buenas @pedroprieto He realizado el ultimo commit de la tarea Fundamentos de JS I, pero no consigo hacer la Pul Request com ote he comentado, hara la parte II y si no puedo hacer la Pull Request no enviare el commit como que ya la termine.
Saludos.

**Comment by pedroprieto** [comment]
Buenas,

No te dejaba porque tenías una abierta. Ya la he cerrado. Abre una nueva PR cuando hayas acabado la parte II.

Un saludo!

**Comment by Luis-Rodes** [comment]
ah vale ok,
