### ISSUE TITLE
Agrupar Gastos

### ISSUE THREAD

**Issue by Luis-Rodes** [Luis-Rodes/practica_dwec_gestor_presupuesto#2]
Buenas @pedroprieto estoy intentando hacer la funcion de agrupar gastos y creo que no me suma los gastos.
No consigo muy bien entender el concepto de la suma del acumulador y creo que ahi esta el fallo.
Le podrias dar un vistazo y ver donde tengo el fallo?
Gracias pedro
https://github.com/Luis-Rodes/practica_dwec_gestor_presupuesto/blob/a65ba47c088c0c798d5a999f127eab401ebc5ce3/js/gestionPresupuesto.js#L116
Esta es la función

**Comment by pedroprieto** [comment]
Buenas,

Te falta pasar un objeto vacío como segundo parámetro a `reduce`. Repasa la grabación de la tutoría.

También te falta inicializar `acc[sumaPeriodo]` antes de utilizarla: en ambos casos haces referencia a ella, exista o no:
https://github.com/Luis-Rodes/practica_dwec_gestor_presupuesto/blob/a65ba47c088c0c798d5a999f127eab401ebc5ce3/js/gestionPresupuesto.js#L130

Lo dicho: repasa el vídeo de la tutoría.

Un saludo!!

**Comment by Luis-Rodes** [comment]
Vale, llevo todo el finde viendo el video, cambiando codigo y nada, el resultado siempre es el mismo.
Seguire intentandolo.
Gracias.

**Comment by pedroprieto** [comment]
Intenta hacerlo en dos pasos: primero, comprueba si el acumulador contiene la entrada (con un `if`).

Ánimo! :muscle:

**Comment by Luis-Rodes** [comment]
ok
