### ISSUE TITLE
Actualizar presupuesto

### ISSUE THREAD

**Issue by Luis-Rodes** [Luis-Rodes/practica_dwec_gestor_presupuesto#3]
Buenas @pedroprieto he creado la función actualizar presupuesto y el botón y el test lo pasa.
Pero no se porque me lo pide tres veces el presupuesto
Es lo creado en esta línea.
Me podrías decir porque pasa esto?
https://github.com/Luis-Rodes/practica_dwec_gestor_presupuesto/blob/1901cea98cc04b7dc35b196d1c2def12b556f3a1/js/gestionPresupuestoWeb.js#L114
Gracias.

**Comment by pedroprieto** [comment]
Buenas,

Declaras la función (y también la de `repintar`) dentro de `mostrarGastosAgrupadosWeb`. Como esa función se llama 3 veces, ahí lo tienes :wink: 

Muévelas fuera y ya está.

Un saludo!!

**Comment by Luis-Rodes** [comment]
Buenos días, no lo entendía lo que me decías, pero me he acordado que me salto un error de código y era por el cierre de una llave y pensé que era la del final.
Arreglado, gracias
