### ISSUE TITLE
Duda npm test

### ISSUE THREAD

**Issue by Luis-Rodes** [Luis-Rodes/practica_dwec_gestor_presupuesto#4]
Buenas Pedro, una duda, cuando ejecuto el comando npm test para comprobar que me pasa los primeros test, nunca me lo hace, siempre me salta algún error antes.
¿Es normal por no tener toda la estructura hecha?
Por ejemplo a esta altura de practica lo he vuelto a realizar y me salta el siguiente error:
<pre>npm test

> practica_dwec_gestor_presupuesto@1.0.0 test
> mocha

file:///F:/cfgs2324/presupuesto/practica_dwec_gestor_presupuesto/test/07_testRegexp.js:3
import {transformarListadoEtiquetas} from "../js/gestionPresupuesto.js";
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '../js/gestionPresupuesto.js' does not provide an export named 'transformarListadoEtiquetas'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
</pre>
Y ya no me da ningún resultado de los demás test, solo ese fallo del test7

Gracias

**Comment by Luis-Rodes** [comment]
Buenas @pedroprieto me imagino que al no nombrarte no viste esto o vas liado con los examenes que es normal.
Pero lo dicho a ver si podemos tener una reunion y vemos el examen y asi aclaro dudas.
Ya me dices Saludos.

**Comment by pedroprieto** [comment]
Buenas,

Efectivamente, no me llegó el aviso porque no me nombraste en el primer mensaje. Acuérdate de hacerlo porque si no lo haces, no tengo manera de ver las notificaciones.

Con respecto a tu error, el problema es que es un error de sintaxis: por eso no ejecuta nada más del código.

Ese error te aparece porque la función `transformarListadoEtiquetas` no está exportada en el fichero `gestionPresupuesto.js`.

Añádela al `export` y se ejecutará.

Un saludo!!

**Comment by Luis-Rodes** [comment]
Ok @pedroprieto  lo he probado y me ha saltado también cargarGastos, las he creado vacías y exportado y  ya funciona.
Gracias
